### PR TITLE
Fix GHA MySQL password

### PR DESCRIPTION
**Pull request by szepeviktor**
@overclokk Please see https://github.com/ItalyStrap/italystrap/runs/3717602467

### CODE REVIEW

**Comment by szepeviktor** [comment]
New Ubuntu https://docs.github.com/en/enterprise-server@2.22/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idruns-on

**Comment by szepeviktor** [comment]
Codeception still fails :(

**Comment by overclokk** [comment]
@szepeviktor Thank you, I know that it does not work yet, I still refactoring the theme to make it compatible with the WP 5.9 and FSE, maybe it will change a lot of code and some test will be removed.

**Comment by szepeviktor** [comment]
All right!

**Pull request closed without merging**
